### PR TITLE
replaced npm and added dev profiles

### PR DESCRIPTION
**Pull request by ennerf**
Nice work! 

I'm not a designer, but seeing your themes made me want to learn more about sass. I found the npm requirement a bit annoying though, so I wrote a tiny maven plugin ([sass-cli-maven-plugin](https://github.com/HebiRobotics/sass-cli-maven-plugin)) that downloads an appropriate dart-sass binary and executes it with user provided args. IMO this results in a much cleaner integration. 

I used your project for testing the plugin on Windows / Linux / macOS, and as far as I can tell the behavior is still correct.

I also added maven profiles for enabling hot reload without requiring extra scripts, so `dev` mode can be enabled directly from maven:

```shell
# run sampler app in dev mode
mvn javafx:run -pl sampler -Pdev

# run hot reload sass
mvn compile -pl styles -Pdev
```

I hope this helps

### CODE REVIEW

**Comment by mkpaz** [comment]
Thanks! That's a really great job, and it's exactly what I searched for when I started the project. There is, however, one unresolved issue. I want to allow users to build custom themes based on AtlantaFX SASS. To achieve this, one should either download and copy `styles/` from project repository, which isn't very convenient, or use package manager. I can't publish SASS on Maven Central because Dart Sass can't import from JAR anyway, so I had plans to publish `styles` module to the NPM repo just for that purpose. Though it won't happen in the near future. But I agree that your plugin makes the build much cleaner and easier to support, and I can still use global NPM for publishing. Sorry, I can't merge this PR immediately because I need some time to check and adapt the new build process. I will return to it as soon as I finish with `showcase` branch. Thanks again for your work.

**Comment by ennerf** [comment]
Fwiw, I think it would be easier to use the `unpack` goal of the [maven-dependency-plugin](https://maven.apache.org/plugins/maven-dependency-plugin/examples/unpacking-artifacts.html) to unpack the scss files from the jar, e.g., something like

```xml
<!-- Unpack styles jar -->
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-dependency-plugin</artifactId>
    <version>3.3.0</version>
    <executions>
        <execution>
            <id>unpack</id>
            <phase>prepare-package</phase>
            <goals>
                <goal>unpack</goal>
            </goals>
            <configuration>
                <artifactItems>
                    <artifactItem>
                        <groupId>${source.groupId}</groupId>
                        <artifactId>${source.artifactId}</artifactId>
                        <version>${source.version}</version>
                        <type>jar</type>
                        <overWrite>true</overWrite>
                        <outputDirectory>${project.build.outputDirectory}/styles</outputDirectory>
                    </artifactItem>
                </artifactItems>
            </configuration>
        </execution>
    </executions>
</plugin>
```

and then add the output as an additional load path for `sass`, e.g., `--load-path=${project.build.outputDirectory}/styles/<path-in-jar>`

**Comment by mkpaz** [comment]
Works like a charm, thanks! It's even faster than Grunt-based workflow.

**Comment by ennerf** [comment]
I saw that you added the `scss` files to the styles jar, and I tried using it as a dependency for an old demo app (see [here](https://github.com/ennerf/HdrHistogramVisualizer/blob/atlantafx-theme/pom.xml#L147-L192)). The whole sass generation works, but actually developing a theme is difficult due to cssfx not reloading useragent stylesheets. I tried developing a theme using the sampler app, but it looks like the dev mode is currently broken due to directory issues (`theme-test` is missing/not being generated).

The code needed for extracting the sass files and using it as a library is

```xml
<properties>
    <atlantafx.version>1.0.0</atlantafx.version>
    <atlantafx.scssDir>${project.build.directory}/atlantafx/styles/</atlantafx.scssDir>
    <scss.inputDir>${project.basedir}/src/main/resources/styles/</scss.inputDir>
    <css.outputDir>${scss.inputDir}</css.outputDir>
</properties>
```

```xml
<plugin> <!-- unpack sass files for theme dev -->
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-dependency-plugin</artifactId>
    <version>3.3.0</version>
    <executions>
        <execution>
            <id>unpack</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>unpack</goal>
            </goals>
            <configuration>
                <artifactItems>
                    <artifactItem>
                        <groupId>io.github.mkpaz</groupId>
                        <artifactId>atlantafx-styles</artifactId>
                        <version>${atlantafx.version}</version>
                        <includes>atlantafx/styles/**</includes>
                        <outputDirectory>${project.build.directory}</outputDirectory>
                    </artifactItem>
                </artifactItems>
            </configuration>
        </execution>
    </executions>
</plugin>

<plugin> <!-- Sass w/ atlantafx lib -->
    <groupId>us.hebi.sass</groupId>
    <artifactId>sass-cli-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>run-sass</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>run</goal>
            </goals>
            <configuration>
                <args>
                    <arg>${scss.inputDir}:${css.outputDir}</arg>
                    <arg>-I${atlantafx.scssDir}</arg>
                    <arg>--no-source-map</arg>
                </args>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by mkpaz** [comment]
Yes, there's no good support for creating custom theme from the SASS sources yet. I've just finished the docs and created a [sample theme repository](https://github.com/mkpaz/atlantafx-sample-theme) that uses the code snippet you shared earlier. (thanks for the great idea!) I do have plans to implement external theme support in Sampler, but a bit later.

**Pull request merged**
